### ISSUE TITLE
[JSSCP][Phulwari] Implement Attendance for Phulwari.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#110]
**Tasks -** 
- [ ] Add **_Phulwari Registration_** form - https://docs.google.com/spreadsheets/d/14fvLwLFfPd50uPhashTGta5rf9S1ItG2H3LOt9vK_tc/edit#gid=578912605
- [ ] Add **_Daily Attendance_** Form - https://docs.google.com/spreadsheets/d/14fvLwLFfPd50uPhashTGta5rf9S1ItG2H3LOt9vK_tc/edit#gid=1062675023
- [ ] Add **_Cancel_** form - https://docs.google.com/spreadsheets/d/14fvLwLFfPd50uPhashTGta5rf9S1ItG2H3LOt9vK_tc/edit#gid=318355191
- [ ] Visit Scheduling - https://docs.google.com/spreadsheets/d/14fvLwLFfPd50uPhashTGta5rf9S1ItG2H3LOt9vK_tc/edit#gid=1842605902
