### ISSUE TITLE
[JSSCP] UAT feedback for Epilepsy 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#140]
feedback - https://docs.google.com/spreadsheets/d/1c_llCuCl-l_BQ1a92riBbBVZ0OGbzi20Xm350DP4Zqk/edit#gid=53734886

Requirement - https://docs.google.com/spreadsheets/d/1nCI079lBmUzNUA4KOB3fdMn7nz7EKVc6sk8RLycL56w/edit#gid=956032555

**To-do -** 
**Enrolment form**
- [x] Row 13 to 23, Add two questions for each medicine.
- [x] Remove question - Member of peer group. Row 7.
- [x] Add FEG- Medicine. From row 11 to 23.

**Followup form -** 
- [x] Add question - Member of support group. Row 9.
- [x] Add new questions - Row 10, 11 and 12. Doing well, Any complaint, aIf yes, what complaint?
- [x] Add new questions row 15 to 18.
- [x] Add row 30 -Patient treatment status.
- [x] Remove question "Need to change the dose/medicine" - Row 45.
- [x] Row 34 to 44, Add two questions for each medicine.
