### ISSUE TITLE
[JSSCP] Diabetes UAT feedback II

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/JSSCP#150]
feedback - https://docs.google.com/spreadsheets/d/1c_llCuCl-l_BQ1a92riBbBVZ0OGbzi20Xm350DP4Zqk/edit#gid=1153821236

Requirement sheet - https://docs.google.com/spreadsheets/d/1nCI079lBmUzNUA4KOB3fdMn7nz7EKVc6sk8RLycL56w/edit#gid=934442207

**To-do -** 
**Form- Diabetes Followup**
- [x] Make the physical examination annual check. (eye, teeth, nail, radial/dorsalis pedis, sensory charting). Row 25, 26, 27, 28, 29, 30.
- [x] Please remove RBS in the follow-up visit. Row 35
- [x] Medicine Related point is not clear. Ravi will confirm. covered in other card #153
**Form - Lab test result.**
- [x] Do not schedule it after the first followup. It needs to be scheduled after 6 months. and then bases on Lab test required.
**Program Summary -** 
- [x] Add these in the summary - FBS, PP2BS, New complications,

**Comment by garimadosar5** [comment]
QA Notes - 
- Row 109 to 117 are missing. 3 medicine related questions are missing.

**Comment by sachsk** [comment]
On hold 
medicines strenght is not present in sheet
