### ISSUE TITLE
[JSSCP Support] Debug and Fix rule failure 3782cd68-addc-4490-b41f-80dc32f5cd2e

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#335]
## Rule uuid 
`3782cd68-addc-4490-b41f-80dc32f5cd2e`

## Context 
As per stacktrace, this rule failure is due to offline report card  - "No of children went into lower grade"

## Error message is
Cannot read property 'getObservationReadableValue' of undefined

## Tasks 

- [x] Debug and fix the rule on JSSCP UAT org
- [ ] After QA is done, move the fix to prod
- [x] Mark all the rule with this uuid as closed.

**Comment by Gojo-Taqi** [comment]
Fixed for org jsscpuat_new.

**Comment by Gojo-Taqi** [comment]
The line of code fixed is this one below.
if(!_.isNil(latestEncounter1) && !_.isNil(latestEncounter2))
It was not checking if the latestEncounters were defined or not.

The issue also occurred because of "ruleServiceLibraryInterfaceForSharingModules", which was later fixed by running the the script available on readme.
https://avni.readme.io/docs/updating-rules-in-bulk
