### ISSUE TITLE
[JSSCP Support] Debug & fix rule failure de331278-bb9a-43fa-9226-c9b08bcce400

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/JSSCP#336]
## Rule uuid 
`de331278-bb9a-43fa-9226-c9b08bcce400`

## Context 
As per stacktrace, this rule failure is due to offline report card  - "No of children in the same grade"

## Error message is
Cannot read property 'getObservationReadableValue' of undefined

## Tasks 

- [x] Debug and fix the rule on JSSCP UAT org
- [x] After QA is done, move the fix to prod
- [x] Mark all the rule with this uuid as closed.

**Comment by Gojo-Taqi** [comment]
Fixed for org jsscpuat_new.

**Comment by Gojo-Taqi** [comment]
The line of code fixed is this one below.
`if(!_.isNil(latestEncounter1) && !_.isNil(latestEncounter2))`
It was not checking if the latestEncounters were defined or not.

The issue also occurred because of "ruleServiceLibraryInterfaceForSharingModules", which was later fixed by running the the script available on readme.
https://avni.readme.io/docs/updating-rules-in-bulk

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal you can move the changes to prod
